src/Entity/Employee.php
<?php

namespace App\Entity;

use App\Repository\EmployeeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmployeeRepository::class)]
class Employee
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(length: 50)]
    private ?string $firstName = null;

    #[ORM\Column(length: 50)]
    private ?string $Grade = null;

    #[ORM\Column(length: 10)]
    private ?string $phone = null;

    #[ORM\Column(length: 50)]
    private ?string $affiliation = null;

    #[ORM\Column(length: 50)]
    private ?string $userName = null;

    #[ORM\Column(length: 50)]
    private ?string $services = null;

    #[ORM\Column(length: 50)]
    private ?string $lieu = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $vehicule = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $detail = null;

    #[ORM\Column]
    private ?bool $isService = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $start_at = null;

    #[ORM\Column(type: Types::INTEGER, nullable: true)]
    private ?int $tss = null;

    #[ORM\Column(nullable: true)]
    private ?int $lastTss = null;

    #[ORM\Column(nullable: true)]
    private ?int $totalTss = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $faru = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $mtt = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $asg = null;

    #[ORM\Column]
    private ?bool $pss = null;

    #[ORM\Column]
    private ?bool $gos = null;

    #[ORM\Column]
    private ?bool $gss = null;

    #[ORM\Column]
    private ?bool $ams = null;

    #[ORM\Column]
    private ?bool $vms = null;

    #[ORM\Column]
    private ?bool $emt = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $ed = null;

    #[ORM\Column]
    private ?bool $dsi = null;

    #[ORM\Column]
    private ?bool $zd = null;

    #[ORM\Column]
    private ?bool $amf = null;

    #[ORM\Column]
    private ?bool $fpc = null;

    #[ORM\Column]
    private ?bool $techasg = null;

    #[ORM\Column]
    private ?bool $sf = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getGrade(): ?string
    {
        return $this->Grade;
    }

    public function setGrade(string $Grade): static
    {
        $this->Grade = $Grade;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAffiliation(): ?string
    {
        return $this->affiliation;
    }

    public function setAffiliation(string $affiliation): static
    {
        $this->affiliation = $affiliation;

        return $this;
    }

    public function getUserName(): ?string
    {
        return $this->userName;
    }

    public function setUserName(string $userName): static
    {
        $this->userName = $userName;

        return $this;
    }

    public function getServices(): ?string
    {
        return $this->services;
    }

    public function setServices(string $services): static
    {
        $this->services = $services;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): static
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getVehicule(): ?string
    {
        return $this->vehicule;
    }

    public function setVehicule(?string $vehicule): static
    {
        $this->vehicule = $vehicule;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): static
    {
        $this->detail = $detail;

        return $this;
    }

    public function isService(): ?bool
    {
        return $this->isService;
    }

    public function setService(bool $isService): static
    {
        $this->isService = $isService;

        return $this;
    }

    public function getStartAt(): ?\DateTimeInterface
    {
        return $this->start_at;
    }

    public function setStartAt(?\DateTimeInterface $start_at): static
    {
        $this->start_at = $start_at;

        return $this;
    }

    public function getTss(): ?int
    {
        return $this->tss;
    }

    public function setTss(?int $tss): static
    {
        $this->tss = $tss;
        return $this;
    }

    public function getLastTss(): ?int
    {
        return $this->lastTss;
    }

    public function setLastTss(?int $lastTss): static
    {
        $this->lastTss = $lastTss;

        return $this;
    }

    public function getTotalTss(): ?int
    {
        return $this->totalTss;
    }

    public function setTotalTss(?int $totalTss): static
    {
        $this->totalTss = $totalTss;

        return $this;
    }

    public function getFaru(): ?string
    {
        return $this->faru;
    }

    public function setFaru(?string $faru): static
    {
        $this->faru = $faru;

        return $this;
    }

    public function getMtt(): ?string
    {
        return $this->mtt;
    }

    public function setMtt(?string $mtt): static
    {
        $this->mtt = $mtt;

        return $this;
    }

    public function getAsg(): ?string
    {
        return $this->asg;
    }

    public function setAsg(?string $asg): static
    {
        $this->asg = $asg;

        return $this;
    }

    public function isPss(): ?bool
    {
        return $this->pss;
    }

    public function setPss(bool $pss): static
    {
        $this->pss = $pss;

        return $this;
    }

    public function isGos(): ?bool
    {
        return $this->gos;
    }

    public function setGos(bool $gos): static
    {
        $this->gos = $gos;

        return $this;
    }

    public function isGss(): ?bool
    {
        return $this->gss;
    }

    public function setGss(bool $gss): static
    {
        $this->gss = $gss;

        return $this;
    }

    public function isAms(): ?bool
    {
        return $this->ams;
    }

    public function setAms(bool $ams): static
    {
        $this->ams = $ams;

        return $this;
    }

    public function isVms(): ?bool
    {
        return $this->vms;
    }

    public function setVms(bool $vms): static
    {
        $this->vms = $vms;

        return $this;
    }

    public function isEmt(): ?bool
    {
        return $this->emt;
    }

    public function setEmt(bool $emt): static
    {
        $this->emt = $emt;

        return $this;
    }

    public function getEd(): ?string
    {
        return $this->ed;
    }

    public function setEd(?string $ed): static
    {
        $this->ed = $ed;

        return $this;
    }

    public function isDsi(): ?bool
    {
        return $this->dsi;
    }

    public function setDsi(bool $dsi): static
    {
        $this->dsi = $dsi;

        return $this;
    }

    public function isZd(): ?bool
    {
        return $this->zd;
    }

    public function setZd(bool $zd): static
    {
        $this->zd = $zd;

        return $this;
    }

    public function isAmf(): ?bool
    {
        return $this->amf;
    }

    public function setAmf(bool $amf): static
    {
        $this->amf = $amf;

        return $this;
    }

    public function isFpc(): ?bool
    {
        return $this->fpc;
    }

    public function setFpc(bool $fpc): static
    {
        $this->fpc = $fpc;

        return $this;
    }

    public function isTechasg(): ?bool
    {
        return $this->techasg;
    }

    public function setTechasg(bool $techasg): static
    {
        $this->techasg = $techasg;

        return $this;
    }

    public function isSf(): ?bool
    {
        return $this->sf;
    }

    public function setSf(bool $sf): static
    {
        $this->sf = $sf;

        return $this;
    }
}

src/Controller/GestEmployeeController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Employee;
use App\Form\EmployeeType;
use App\Form\NewEmployeeType;
use App\Repository\EmployeeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class GestEmployeeController extends AbstractController
{
    #[IsGranted('ROLE_ADMIN')]
    #[Route('/employees', name: 'app_employee_index')]
    public function index(EmployeeRepository $employeeRepository): Response
    {
        // Récupération de tous les employés
        $employees = $employeeRepository->findAll();

        // Rendu de la vue avec la liste des employés
        return $this->render('prive/pages/gest_employee/index.html.twig', [
            'employees' => $employees,
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/employees/new', name: 'app_employee_new')]
    public function new(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher,): Response
    {
        // Création d'un nouvel employé
        $employee = new Employee();

        // Création du formulaire
        $form = $this->createForm(NewEmployeeType::class, $employee);

        // Gestion de la requête POST
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $employee->setService(false);
            $employee->setStartAt(new \DateTime('now'));
            $employee->setTss(0);
            $employee->setServices('Code 6');
            $employee->setLieu('Los Santos');
            $employee->setVehicule('Aucun');

            // creation de l'user
            $user = new User();
            $user->setUsername($employee->getUserName());
            $user->setRoles(['ROLE_USER']);

            $username = $user->getUsername();
            $encodedPassword = $passwordHasher->hashPassword($user, $username);
            $user->setPassword($encodedPassword);
            $entityManager->persist($user);
            $entityManager->persist($employee);
            $entityManager->flush();

            // Redirection avec un message de succès
            $this->addFlash('success', 'L\'employé a été ajouté.');

            return $this->redirectToRoute('app_employee_index');
        }

        // Rendu de la vue avec le formulaire
        return $this->render('prive/pages/gest_employee/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/employees/{id}/edit', name: 'app_employee_edit')]
    public function edit(
        Employee $employee,
        Request $request,
        EntityManagerInterface $entityManager
    ): Response {
        // Création du formulaire avec les données de l'employé
        $form = $this->createForm(EmployeeType::class, $employee);

        // Gestion de la requête POST
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Sauvegarde des modifications
            $entityManager->flush();

            // Redirection avec un message de succès
            $this->addFlash('success', 'Les informations de l\'employé ont été mises à jour.');

            return $this->redirectToRoute('app_employee_index');
        }

        // Rendu de la vue avec le formulaire et l'employé
        return $this->render('prive/pages/gest_employee/edit.html.twig', [
            'form' => $form->createView(),
            'employee' => $employee,
        ]);
    }


    #[IsGranted('ROLE_ADMIN')]
    #[Route('/employees/{id}/delete', name: 'app_employee_delete', methods: ['POST'])]
    public function delete(
        Request $request,
        Employee $employee,
        EntityManagerInterface $entityManager
    ): Response {
        // Vérification du token CSRF
        if ($this->isCsrfTokenValid('delete' . $employee->getId(), $request->request->get('_token'))) {
            // Suppression de l'employé
            $entityManager->remove($employee);
            $entityManager->flush();

            // Redirection avec un message de succès
            $this->addFlash('success', 'L\'employé a été licencié.');
        }

        return $this->redirectToRoute('app_employee_index');
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/employees/{id}', name: 'app_employee_show', methods: ['GET'])]
    public function show(Employee $employee): Response
    {
        return $this->render('prive/pages/gest_employee/show.html.twig', [
            'employee' => $employee,
        ]);
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/employees/retrait-service/{id}', name: 'app_employee_retrait_service', methods: ['GET'])]
    public function retraitService(Employee $employee, EntityManagerInterface $entityManager): Response
    {
        // Retrait du service
        $employee->setService(false);
        $entityManager->flush();

        // Redirection avec un message de succès
        $this->addFlash('success', 'L\'employé a été retiré du service.');

        return $this->redirectToRoute('app_employee_index');
    }

    #[IsGranted('ROLE_ADMIN')]
    #[Route('/employees/ajout-service/{id}', name: 'app_employee_ajout_service', methods: ['GET'])]
    public function ajoutService(Employee $employee, EntityManagerInterface $entityManager): Response
    {
        // Ajout du service
        $now = new \DateTime('now');
        $employee->setStartAt($now);
        $employee->setService(true);
        $entityManager->flush();

        // Redirection avec un message de succès
        $this->addFlash('success', 'L\'employé a été ajouté au service.');

        return $this->redirectToRoute('app_employee_index');
    }
}

templates/prive/pages/gest_employee/edit.html.twig
{# templates/employee/edit.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}LSMC | Modifier Employé{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1>Modifier Employé</h1>

    {{ form_start(form, {'attr': {'class': 'needs-validation', 'novalidate': 'novalidate'}}) }}

    <div class="card shadow-sm mb-4">
        <div class="card-body">
            <div class="row mb-3">
                <div class="col-md-6">
                    <div class="mb-3">
                        {{ form_label(form.name, null, {'attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.name, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.name) }}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.firstName, null, {'attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.firstName, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.firstName) }}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.phone, null, {'attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.phone, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.phone) }}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.userName, null, {'attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.userName, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.userName) }}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="mb-3">
                        {{ form_label(form.Grade, null, {'attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.Grade, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.Grade) }}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.affiliation, null, {'attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.affiliation, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.affiliation) }}
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-md-6">
                    <div class="mb-3">
                        {{ form_label(form.start_at, null, {'attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.start_at, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.start_at) }}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.tss, null, {'attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.tss, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.tss) }}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.lastTss, null, {'attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.lastTss, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.lastTss) }}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.totalTss, null, {'attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.totalTss, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.totalTss) }}
                    </div>
                </div>

                <div class="col-md-6">
                    <div class="mb-3">
                        {{ form_label(form.faru, null, {'attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.faru, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.faru) }}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.mtt, null, {'attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.mtt, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.mtt) }}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.asg, null, {'attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.asg, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.asg) }}
                    </div>
                    <div class="mb-3">
                        {{ form_label(form.ed, null, {'attr': {'class': 'form-label'}}) }}
                        {{ form_widget(form.ed, {'attr': {'class': 'form-control'}}) }}
                        {{ form_errors(form.ed) }}
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-md-12">
                    <h5>Services hospitaliers</h5>
                    <div class="form-check form-check-inline">
                        {{ form_widget(form.pss) }}
                        {{ form_label(form.pss, null, {'attr': {'class': 'form-check-label'}}) }}
                    </div>
                    <div class="form-check form-check-inline">
                        {{ form_widget(form.gos) }}
                        {{ form_label(form.gos, null, {'attr': {'class': 'form-check-label'}}) }}
                    </div>
                    <div class="form-check form-check-inline">
                        {{ form_widget(form.gss) }}
                        {{ form_label(form.gss, null, {'attr': {'class': 'form-check-label'}}) }}
                    </div>
                    <div class="form-check form-check-inline">
                        {{ form_widget(form.ams) }}
                        {{ form_label(form.ams, null, {'attr': {'class': 'form-check-label'}}) }}
                    </div>
                    <div class="form-check form-check-inline">
                        {{ form_widget(form.vms) }}
                        {{ form_label(form.vms, null, {'attr': {'class': 'form-check-label'}}) }}
                    </div>
                    <div class="form-check form-check-inline">
                        {{ form_widget(form.emt) }}
                        {{ form_label(form.emt, null, {'attr': {'class': 'form-check-label'}}) }}
                    </div>
                </div>
                    <div class="col-md-12">
                    <h5>Certifications</h5>
                    <div class="form-check form-check-inline">
                        {{ form_widget(form.dsi) }}
                        {{ form_label(form.dsi, null, {'attr': {'class': 'form-check-label'}}) }}
                    </div>
                    <div class="form-check form-check-inline">
                        {{ form_widget(form.zd) }}
                        {{ form_label(form.zd, null, {'attr': {'class': 'form-check-label'}}) }}
                    </div>
                    <div class="form-check form-check-inline">
                        {{ form_widget(form.amf) }}
                        {{ form_label(form.amf, null, {'attr': {'class': 'form-check-label'}}) }}
                    </div>
                    <div class="form-check form-check-inline">
                        {{ form_widget(form.fpc) }}
                        {{ form_label(form.fpc, null, {'attr': {'class': 'form-check-label'}}) }}
                    </div>
                    <div class="form-check form-check-inline">
                        {{ form_widget(form.techasg) }}
                        {{ form_label(form.techasg, null, {'attr': {'class': 'form-check-label'}}) }}
                    </div>
                    <div class="form-check form-check-inline">
                        {{ form_widget(form.sf) }}
                        {{ form_label(form.sf, null, {'attr': {'class': 'form-check-label'}}) }}
                    </div>
                    </div>
                </div>
            </div>

            <div class="row mb-3">
                <div class="col-md-6">
                    <a href="{{ path('app_employee_retrait_service', { id: employee.id }) }}" class="btn btn-dark">Retirer service en cours</a>
                    <a href="{{ path('app_employee_ajout_service', { id: employee.id }) }}" class="btn btn-dark">Mettre en service</a>
                </div>
            </div>
        </div>
        <div class="card-footer text-end">
            <button type="submit" class="btn btn-primary">Sauvegarder</button>
            <a href="{{ path('app_employee_index') }}" class="btn btn-secondary">Retour à la liste</a>
        </div>
    </div>

    {{ form_end(form) }}
</div>
{% endblock %}

templates/prive/pages/gest_employee/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}LSMC | Liste des Employés{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1>Liste des Employés</h1>
    <a href="{{ path('app_employee_new') }}" class="btn btn-primary mb-3">Ajouter un employé</a>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Grade</th>
                <th>Unité</th>
                <th>Agrégation</th>
                <th></th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for employee in employees %}
                <tr>
                    <td>{{ employee.id }}</td>
                    <td>{{ employee.name }}</td>
                    <td>{{ employee.firstName }}</td>
                    <td>{{ employee.Grade }}</td>
                    <td>/</td>
                    <td>/</td>
                    <td>
                        {% if employee.isService %}
                            <span class="badge bg-success text-white">En service</span>
                        {% else %}
                            <span class="badge bg-danger text-white">Hors service</span>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{{ path('app_employee_show', { id: employee.id }) }}" class="btn btn-info btn-sm">Voir les détails</a>
                        <a href="{{ path('app_employee_edit', { id: employee.id }) }}" class="btn btn-warning btn-sm">Modifier</a>
                        <form action="{{ path('app_employee_delete', { id: employee.id }) }}" method="post" style="display:inline;" onsubmit="return confirm('Êtes-vous sûr de vouloir licencier cet employé ?');">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employee.id) }}">
                            <button class="btn btn-danger btn-sm" type="submit">Licencier</button>
                        </form>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">Aucun employé trouvé</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/prive/pages/gest_employee/show.html.twig
{# templates/employee/show.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}LSMC | Détails de l'Employé{% endblock %}

{% block body %}
<div class="container mt-5">
    <h1 class="mb-4">Détails de l'Employé</h1>

    <div class="card shadow-sm mb-4">
        <div class="card-header bg-primary text-white">
            <h5 class="card-title mb-0">Employé ID: {{ employee.id }}</h5>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-md-6">
                    <p><strong>Nom:</strong> {{ employee.name }}</p>
                    <p><strong>Prénom:</strong> {{ employee.firstName }}</p>
                    <p><strong>Grade:</strong> {{ employee.grade }}</p>
                    <p><strong>Agregation:</strong> /</p>
                    <p><strong>Unite:</strong> /</p>
                </div>
                <div class="col-md-6">
                    <p><strong>Téléphone:</strong> {{ employee.phone }}</p>
                    <p><strong>Affiliation:</strong> {{ employee.affiliation }}</p>
                    <p><strong>Nom d'utilisateur:</strong> {{ employee.userName }}</p>
                    <p><strong>Services:</strong> {{ employee.services }}</p>
                    <p><strong>Lieu:</strong> {{ employee.lieu }}</p>
                    <p><strong>Véhicule:</strong> {{ employee.vehicule }}</p>
                </div>
            </div>
            <hr>
            <p><strong>Détails:</strong> {{ employee.detail }}</p>
            <p><strong>Date de début:</strong> {{ employee.startAt ? employee.startAt|date('d/m/Y H:i') : 'N/A' }}</p>
            <p><strong>TSS:</strong> {{ employee.tss }}</p>
            <p><strong>Dernier TSS:</strong> {{ employee.lastTss }}</p>
            <p><strong>Total TSS:</strong> {{ employee.totalTss }}</p>
        </div>
        <div class="card-footer d-flex justify-content-between">
            <a href="{{ path('app_employee_edit', { id: employee.id }) }}" class="btn btn-warning">Modifier</a>

            <!-- Formulaire de suppression avec confirmation -->
            <form action="{{ path('app_employee_delete', { id: employee.id }) }}" method="post" onsubmit="return confirm('Êtes-vous sûr de vouloir licencier cet employé ?');">
                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ employee.id) }}">
                <button class="btn btn-danger" type="submit">Supprimer</button>
            </form>
            
            <a href="{{ path('app_employee_index') }}" class="btn btn-primary">Retour à la liste</a>
        </div>
    </div>

    <!-- Espacement sous la carte -->
    <div class="mb-5"></div>
</div>
{% endblock %}